import { CampSite } from "./types";

/**
 * Curated starter data focused on Chattahoochee-Oconee National Forest
 * and nearby options accessible from the Conyers / Stockbridge / Vidalia area.
 * Drive times approximate from metro Atlanta / Conyers.
 */
export const mockSites: CampSite[] = [
  {
    id: "desoto-falls",
    name: "Desoto Falls Recreation Area",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    lat: 34.712,
    lng: -83.915,
    elevation: 2200,
    driveTimeMinutes: 105,
    hikeInMiles: 0.1,
    hikeInElevationGain: 20,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov/camping/campgrounds/232290",
    bookingWindow: "6 months rolling",
    passRequired: "None for camping (America the Beautiful covers day-use elsewhere)",
    parkingFee: "Included with camping",
    campingFee: "$20–$40 / night",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Vault toilets", "Water", "Short waterfall trail"],
    mustSees: ["Desoto Falls (upper & lower)", "Easy waterfall hike", "Mountain stream"],
    description:
      "Popular developed campground with easy access to a beautiful double waterfall. Great first trip into the mountains — short hike to the falls right from the area.",
    notes: "Fills quickly on weekends. Book early or aim for mid-week.",
  },
  {
    id: "ball-field-dispersed",
    name: "Ball Field Dispersed Camping Area",
    type: "dispersed",
    agency: "USFS — Chattahoochee-Oconee NF (Conasauga RD)",
    lat: 34.8609,
    lng: -84.6362,
    elevation: 3200,
    driveTimeMinutes: 150,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "None",
    parkingFee: "Free (nearby Lake Conasauga day-use $5 if using those facilities)",
    campingFee: "Free",
    maxStayDays: 14,
    amenities: ["Fire rings (established)", "Open field", "Trailheads on site"],
    mustSees: ["Emery Creek Trail", "Tearbritches Trail into Cohutta Wilderness", "Lake Conasauga (1 mile)", "Stargazing"],
    description:
      "Large open grassy field at the base of Bald Mountain. True dispersed feel with established fire rings. Excellent access to Cohutta Wilderness trails. High clearance recommended on the approach road in wet conditions.",
    notes: "No amenities. Pack in / pack out. Great for groups that want space and solitude.",
  },
  {
    id: "tate-branch",
    name: "Tate Branch Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    lat: 34.85,
    lng: -83.55,
    elevation: 2400,
    driveTimeMinutes: 130,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov",
    bookingWindow: "6 months",
    passRequired: "None for camping",
    parkingFee: "Included",
    campingFee: "$15 / night",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Vault toilets", "River access", "4 walk-in tent sites"],
    mustSees: ["Tallulah River confluence", "Quiet mountain stream", "Nearby fishing"],
    description:
      "Quiet 17-site campground at the junction of Tallulah River and Tate Branch. Includes walk-in tent sites for a more rustic feel while still having basic facilities.",
  },
  {
    id: "upper-chattahoochee",
    name: "Upper Chattahoochee River Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    lat: 34.78,
    lng: -83.73,
    elevation: 2800,
    driveTimeMinutes: 120,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov/camping/campgrounds/10309362",
    bookingWindow: "6 months",
    passRequired: "None for camping",
    parkingFee: "Included",
    campingFee: "Check Recreation.gov",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Lantern posts", "Portable toilets", "Trash bins"],
    mustSees: ["Horse Trough Falls (short trail from campground)", "Headwaters of the Chattahoochee", "Scenic FS road approach"],
    description:
      "19-site developed campground near the headwaters of the Chattahoochee. Short walking trail to Horse Trough Falls right from the back of the campground. Beautiful mountain approach.",
  },
  {
    id: "andrews-cove",
    name: "Andrews Cove Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    lat: 34.75,
    lng: -83.75,
    elevation: 2100,
    driveTimeMinutes: 100,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov",
    bookingWindow: "6 months",
    passRequired: "None for camping",
    parkingFee: "Included",
    campingFee: "$12–$18 / night",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Vault toilets", "Streamside sites"],
    mustSees: ["Cool mountain stream", "Close to Helen, GA", "Easy access from Unicoi Gap area"],
    description:
      "Peaceful streamside campground only about 15 minutes from the alpine village of Helen. Good balance of nature immersion and convenience.",
  },
  {
    id: "lake-russell",
    name: "Lake Russell Recreation Area Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    lat: 34.45,
    lng: -83.35,
    elevation: 1100,
    driveTimeMinutes: 90,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov",
    bookingWindow: "Year-round reservable",
    passRequired: "None for camping (Senior/Access get 50% discount)",
    parkingFee: "Included",
    campingFee: "$24 single / $48 double",
    maxStayDays: 14,
    amenities: ["Flush toilets (Loop A)", "Water spigots", "Picnic tables", "Fire rings", "Lake access"],
    mustSees: ["Lake Russell", "Swimming / fishing", "Boat ramp nearby"],
    description:
      "42-site campground on Lake Russell with both tent and RV options. Reservation only. Good for families who want water access without a long drive into the high mountains.",
  },
  {
    id: "jones-creek-dispersed",
    name: "Jones Creek Dispersed",
    type: "dispersed",
    agency: "USFS — Chattahoochee-Oconee NF",
    lat: 34.7,
    lng: -83.9,
    elevation: 1800,
    driveTimeMinutes: 110,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "None",
    parkingFee: "Free",
    campingFee: "Free",
    maxStayDays: 14,
    amenities: ["Creek access", "Some established spots"],
    mustSees: ["Riverside camping", "Quiet forest roads"],
    description:
      "Riverside dispersed sites accessible via a narrow dirt road. More secluded feel. Good for smaller groups and those comfortable with primitive conditions.",
    notes: "Drive the road carefully. Do not park exactly where generic maps sometimes point.",
  },
];

export function getSiteById(id: string): CampSite | undefined {
  return mockSites.find((s) => s.id === id);
}
