import { CampSite } from "./types";
import { privateNatureStays } from "./private-sites";

/**
 * Curated Georgia-focused data so the app is useful immediately.
 * Drive times approximate from metro Atlanta / Conyers area.
 *
 * When RIDB_API_KEY is present, the search API pulls live federal facilities
 * and these curated entries act as enrichment + dispersed/WMA/OHV/private coverage
 * that RIDB does not fully cover.
 */
const publicSites: CampSite[] = [
  {
    id: "desoto-falls",
    name: "Desoto Falls Recreation Area",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.712,
    lng: -83.915,
    elevation: 2200,
    driveTimeMinutes: 105,
    hikeInMiles: 0.1,
    hikeInElevationGain: 20,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov/camping/campgrounds/232290",
    bookingWindow: "6 months rolling",
    passRequired: "None for camping. America the Beautiful covers some day-use elsewhere on the forest",
    parkingFee: "Included with camping",
    campingFee: "$20–$40 / night",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Vault toilets", "Water", "Short waterfall trail"],
    mustSees: ["Desoto Falls (upper & lower)", "Easy waterfall hike", "Mountain stream"],
    description:
      "Popular developed campground with easy access to a beautiful double waterfall. Great first trip into the mountains — short hike to the falls right from the area.",
    notes: "Fills quickly on weekends. Book early or aim for mid-week. Senior/Access passes often get camping discounts.",
    activities: ["Camping", "Hiking", "Waterfall viewing"],
    imageUrl:
      "https://cdn.recreation.gov/public/2019/12/31/14/45/240242_102f6da6-d28b-4493-90e9-00898ef7b466_700.webp",
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "paved",
    pulse: {
      summary: "Busy on weekends; book early. Falls trail short and family-friendly.",
      crowd: "busy",
      lastVerified: "2026-07",
      source: "curated",
    },
  },
  {
    id: "tate-branch",
    name: "Tate Branch Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.85,
    lng: -83.55,
    elevation: 2400,
    driveTimeMinutes: 130,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov",
    bookingWindow: "6 months",
    passRequired: "None for camping",
    parkingFee: "Included",
    campingFee: "$15 / night",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Vault toilets", "River access", "4 walk-in tent sites"],
    mustSees: ["Tallulah River confluence", "Quiet mountain stream", "Nearby fishing"],
    description:
      "Quiet 17-site campground at the junction of Tallulah River and Tate Branch. Includes walk-in tent sites for a more rustic feel while still having basic facilities.",
    activities: ["Camping", "Fishing", "Hiking"],
    imageUrl:
      "https://cdn.recreation.gov/public/2024/03/31/16/07/10309540_dfb0e6c8-24ec-477d-b51c-8f06a50a45e0_1440.webp",
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "gravel",
    pulse: {
      summary: "Quieter than Desoto; good mid-week option.",
      crowd: "moderate",
      lastVerified: "2026-06",
      source: "curated",
    },
  },
  {
    id: "upper-chattahoochee",
    name: "Upper Chattahoochee River Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.78,
    lng: -83.73,
    elevation: 2800,
    driveTimeMinutes: 120,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov/camping/campgrounds/10309362",
    bookingWindow: "6 months",
    passRequired: "None for camping",
    parkingFee: "Included",
    campingFee: "Check Recreation.gov",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Lantern posts", "Portable toilets", "Trash bins"],
    mustSees: ["Horse Trough Falls (short trail from campground)", "Headwaters of the Chattahoochee", "Scenic FS road approach"],
    description:
      "19-site developed campground near the headwaters of the Chattahoochee. Short walking trail to Horse Trough Falls right from the back of the campground. Beautiful mountain approach.",
    activities: ["Camping", "Hiking", "Waterfall viewing"],
    imageUrl:
      "https://cdn.recreation.gov/public/2024/06/18/15/13/10309362_75a79690-ff4f-4e8b-9b7b-4721d81761ba_1440.webp",
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "gravel",
    pulse: {
      summary: "Scenic approach; Horse Trough Falls is the highlight.",
      crowd: "moderate",
      lastVerified: "2026-07",
      source: "curated",
    },
  },
  {
    id: "andrews-cove",
    name: "Andrews Cove Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.75,
    lng: -83.75,
    elevation: 2100,
    driveTimeMinutes: 100,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov",
    bookingWindow: "6 months",
    passRequired: "None for camping",
    parkingFee: "Included",
    campingFee: "$12–$18 / night",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Vault toilets", "Streamside sites"],
    mustSees: ["Cool mountain stream", "Close to Helen, GA", "Easy access from Unicoi Gap area"],
    description:
      "Peaceful streamside campground only about 15 minutes from the alpine village of Helen. Good balance of nature immersion and convenience.",
    activities: ["Camping", "Hiking"],
    imageUrl:
      "https://cdn.recreation.gov/public/2024/06/18/15/51/10309337_163d7ac2-015e-444f-9dec-340aad679acb_1440.webp",
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "paved",
  },
  {
    id: "lake-russell",
    name: "Lake Russell Recreation Area Campground",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.45,
    lng: -83.35,
    elevation: 1100,
    driveTimeMinutes: 90,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov",
    bookingWindow: "Year-round reservable",
    passRequired: "None for camping (Senior/Access often 50% off camping)",
    parkingFee: "Included",
    campingFee: "$24 single / $48 double",
    maxStayDays: 14,
    amenities: ["Flush toilets (Loop A)", "Water spigots", "Picnic tables", "Fire rings", "Lake access"],
    mustSees: ["Lake Russell", "Swimming / fishing", "Boat ramp nearby"],
    description:
      "42-site campground on Lake Russell with both tent and RV options. Reservation only. Good for families who want water access without a long drive into the high mountains.",
    activities: ["Camping", "Fishing", "Boating", "Swimming"],
    imageUrl:
      "https://cdn.recreation.gov/public/2023/06/07/17/39/273781_3d55b312-09bb-4503-9a7e-447071347fe0_700.webp",
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "paved",
  },
  {
    id: "frank-gross",
    name: "Frank Gross Recreation Area",
    type: "developed",
    agency: "USFS — Chattahoochee-Oconee NF (Ed Jenkins NRA)",
    landManager: "USFS",
    lat: 34.65,
    lng: -84.15,
    elevation: 2300,
    driveTimeMinutes: 115,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    reservationUrl: "https://www.recreation.gov",
    bookingWindow: "6 months (April–Oct typically)",
    passRequired: "None for camping",
    parkingFee: "Included",
    campingFee: "$8 / night",
    maxStayDays: 14,
    amenities: ["Picnic tables", "Fire rings", "Vault toilets", "Creek access"],
    mustSees: ["Rock Creek", "Quiet mountain setting", "Fall color"],
    description:
      "Smaller developed campground on Rock Creek in the Ed Jenkins National Recreation Area. Affordable and peaceful — good mid-week escape.",
    activities: ["Camping", "Fishing", "Hiking"],
    imageUrl:
      "https://cdn.recreation.gov/public/2022/10/16/15/45/10203811_caeff718-c919-43bc-924d-7f2eb99bf3e3_700.webp",
    dataSource: "curated",
    status: "seasonal",
    access: "any_vehicle",
    roadQuality: "gravel",
    pulse: {
      summary: "Typically April–Oct; quiet when open.",
      crowd: "quiet",
      lastVerified: "2026-05",
      source: "curated",
    },
  },
  {
    id: "ball-field-dispersed",
    name: "Ball Field Dispersed Camping Area",
    type: "dispersed",
    agency: "USFS — Chattahoochee-Oconee NF (Conasauga RD)",
    landManager: "USFS",
    lat: 34.8609,
    lng: -84.6362,
    elevation: 3200,
    driveTimeMinutes: 150,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "None",
    parkingFee: "Free (Lake Conasauga day-use ~$5 if using those facilities)",
    campingFee: "Free",
    maxStayDays: 14,
    amenities: ["Fire rings (established)", "Open field", "Trailheads on site"],
    mustSees: ["Emery Creek Trail", "Tearbritches Trail into Cohutta Wilderness", "Lake Conasauga (1 mile)", "Stargazing"],
    description:
      "Large open grassy field at the base of Bald Mountain. True dispersed feel with established fire rings. Excellent access to Cohutta Wilderness trails. High clearance recommended on the approach road in wet conditions.",
    notes: "No amenities. Pack in / pack out. Great for groups that want space and solitude.",
    activities: ["Camping", "Hiking", "Wilderness access"],
    ohvFriendly: false,
    dataSource: "curated",
    status: "open",
    access: "high_clearance",
    roadQuality: "rough",
    pulse: {
      summary: "High clearance recommended when wet. True dispersed feel; pack out everything.",
      crowd: "moderate",
      roadNote: "Approach road rough after rain",
      lastVerified: "2026-07",
      source: "curated",
    },
  },
  {
    id: "jones-creek-dispersed",
    name: "Jones Creek Dispersed",
    type: "dispersed",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.7,
    lng: -83.9,
    elevation: 1800,
    driveTimeMinutes: 110,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "None",
    parkingFee: "Free",
    campingFee: "Free",
    maxStayDays: 14,
    amenities: ["Creek access", "Some established spots"],
    mustSees: ["Riverside camping", "Quiet forest roads"],
    description:
      "Riverside dispersed sites accessible via a narrow dirt road. More secluded feel. Good for smaller groups and those comfortable with primitive conditions.",
    notes: "Drive the road carefully. Do not park exactly where generic maps sometimes point.",
    activities: ["Camping", "Fishing"],
    dataSource: "curated",
    status: "open",
    access: "high_clearance",
    roadQuality: "rough",
    pulse: {
      summary: "Narrow dirt access; more secluded than developed sites.",
      crowd: "quiet",
      lastVerified: "2026-06",
      source: "curated",
    },
  },
  {
    id: "hickey-gap",
    name: "Hickey Gap Campground (primitive)",
    type: "dispersed",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.82,
    lng: -84.55,
    elevation: 2800,
    driveTimeMinutes: 145,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "None",
    parkingFee: "Free",
    campingFee: "Free / low fee if marked",
    maxStayDays: 14,
    amenities: ["Creek-side sites", "Small number of spots"],
    mustSees: ["Mills Creek", "Quiet north Georgia mountains"],
    description:
      "Small primitive / dispersed-style sites along Mills Creek. Often quieter alternative near the Ball Field / Lake Conasauga corridor.",
    activities: ["Camping", "Fishing"],
    dataSource: "curated",
    status: "open",
    access: "high_clearance",
    roadQuality: "gravel",
  },
  {
    id: "ocmulgee-flats-wma",
    name: "Ocmulgee Flats Hunt Camp (Oconee NF / WMA area)",
    type: "wma",
    agency: "USFS / Georgia DNR influence",
    landManager: "USFS",
    lat: 33.18,
    lng: -83.82,
    elevation: 450,
    driveTimeMinutes: 75,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "None for camping (hunting seasons have extra rules)",
    parkingFee: "Free",
    campingFee: "Free",
    maxStayDays: 14,
    amenities: ["Primitive sites", "Highlines for horses in some spots"],
    mustSees: ["Ocmulgee River access", "Quiet Piedmont forest"],
    description:
      "Primitive dispersed-style camping in the Oconee portion of the national forest / hunt camp area. Closer to the Atlanta and middle-Georgia side — good for a quicker escape.",
    notes: "Follow all WMA / forest rules. Pack out everything. Check hunting seasons before going.",
    activities: ["Camping", "Hunting (seasonal)", "Hiking", "Fishing"],
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "gravel",
    pulse: {
      summary: "Check hunting seasons before going; quieter outside them.",
      crowd: "quiet",
      lastVerified: "2026-05",
      source: "curated",
    },
  },
  {
    id: "crockford-pigeon-wma",
    name: "Crockford-Pigeon Mountain WMA (Blue Hole area)",
    type: "wma",
    agency: "Georgia DNR",
    landManager: "State DNR / WMA",
    lat: 34.72,
    lng: -85.38,
    elevation: 1400,
    driveTimeMinutes: 130,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "Georgia WMA / land access rules — check current DNR chart",
    parkingFee: "Check current regulations",
    campingFee: "Usually free with proper credentials",
    maxStayDays: 14,
    amenities: ["Primitive / designated spots", "Trail access"],
    mustSees: ["Pigeon Mountain", "Rock formations", "Hiking & caving nearby"],
    description:
      "Wildlife Management Area on the northwest side of Georgia with primitive camping opportunities. Different feel from national forest — more open and rugged in places.",
    notes: "Always verify current Georgia DNR WMA regulations and any required licenses before camping.",
    activities: ["Camping", "Hiking", "Hunting (seasonal)", "Wildlife viewing"],
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "gravel",
  },
  {
    id: "pine-log-wma",
    name: "Pine Log Mountain WMA",
    type: "wma",
    agency: "Georgia DNR",
    landManager: "State DNR / WMA",
    lat: 34.28,
    lng: -84.65,
    elevation: 1200,
    driveTimeMinutes: 70,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "Check Georgia DNR WMA requirements",
    parkingFee: "Varies",
    campingFee: "Usually free with proper credentials",
    maxStayDays: 14,
    amenities: ["Primitive camping", "Trail system"],
    mustSees: ["Pine Log Mountain", "23+ miles of trails", "Closer drive from Atlanta"],
    description:
      "One of the more accessible WMAs north of Atlanta. Trails for hiking and mountain biking plus seasonal hunting. Primitive camping available under DNR rules.",
    notes: "Confirm current camping and pass rules on the Georgia DNR site before you go.",
    activities: ["Camping", "Hiking", "Mountain biking", "Hunting (seasonal)"],
    dataSource: "curated",
    status: "open",
    access: "any_vehicle",
    roadQuality: "gravel",
  },
  {
    id: "houston-valley-ohv",
    name: "Houston Valley OHV Area",
    type: "ohv",
    agency: "USFS — Chattahoochee-Oconee NF (Conasauga RD)",
    landManager: "USFS",
    lat: 34.78,
    lng: -84.95,
    elevation: 900,
    driveTimeMinutes: 100,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    reservationUrl: "https://www.recreation.gov/activitypass/AP21150",
    passRequired: "OHV day pass (~$5/operator) or Annual OHV Pass ($50). Separate from America the Beautiful",
    parkingFee: "Included with riding pass at staging area",
    campingFee: "No camping at staging; dispersed nearby under standard 14-day rules where allowed",
    maxStayDays: 14,
    amenities: ["Paved staging lot", "Loading ramp", "Vault toilets", "Picnic tables", "Kiosk"],
    mustSees: ["Largest FS OHV system in Georgia (~25 miles)", "Easy to difficult trails", "Wooded setting west of Dalton"],
    description:
      "Largest Forest Service OHV trail system in Georgia. Trails range from easy forested routes to steep climbs and occasional mud/water crossings. Vehicles generally limited to ~50\" width. Staging area is paved and handles large trailers.",
    notes:
      "Trails often close after significant rain — call Conasauga Ranger District before you haul. Stay on designated routes only. Annual pass covers several other systems on the forest.",
    activities: ["OHV / ATV", "Motorcycle", "UTV (width limits)"],
    ohvFriendly: true,
    dataSource: "curated",
    status: "open",
    access: "ohv_only",
    roadQuality: "paved",
    pulse: {
      summary: "Call before you haul after rain. Day or annual OHV pass required.",
      crowd: "busy",
      roadNote: "Staging is paved; trails close when wet",
      lastVerified: "2026-07",
      source: "official",
    },
  },
  {
    id: "beasley-knob-ohv",
    name: "Beasley Knob OHV Trail System",
    type: "ohv",
    agency: "USFS — Chattahoochee-Oconee NF (Blue Ridge RD)",
    landManager: "USFS",
    lat: 34.87,
    lng: -83.95,
    elevation: 2000,
    driveTimeMinutes: 120,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "OHV day or annual pass required (check Recreation.gov / ranger station)",
    parkingFee: "At trailheads",
    campingFee: "OHV camping opportunities nearby — check current FS guidance",
    maxStayDays: 14,
    amenities: ["Two trailheads (incl. Satterfield)", "Challenging terrain"],
    mustSees: ["~13 miles of interconnecting trails", "Rock hill climbs", "Near Blairsville"],
    description:
      "Challenging trail system two miles east of Blairsville. Open to four-wheel drive vehicles, ATVs, and motorcycles on designated routes. Recommended for experienced riders; many segments rated difficult to most difficult.",
    notes: "Status can change with weather. Confirm open/closed with Blue Ridge Ranger District before going.",
    activities: ["OHV / 4x4", "ATV", "Motorcycle"],
    ohvFriendly: true,
    dataSource: "curated",
    status: "seasonal",
    access: "4x4",
    roadQuality: "technical",
    pulse: {
      summary: "Experienced riders; weather closures common. Confirm status before going.",
      crowd: "moderate",
      lastVerified: "2026-07",
      source: "official",
    },
  },
  {
    id: "whissenhunt-ohv",
    name: "Whissenhunt OHV Trails",
    type: "ohv",
    agency: "USFS — Chattahoochee-Oconee NF",
    landManager: "USFS",
    lat: 34.6,
    lng: -84.05,
    elevation: 1800,
    driveTimeMinutes: 95,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    reservationUrl: "https://www.recreation.gov",
    passRequired: "1-day OHV pass ~$5/operator or Annual OHV Pass $50",
    parkingFee: "At designated parking on FS 662",
    campingFee: "Not at trailhead; use nearby dispersed or developed sites",
    maxStayDays: 14,
    amenities: ["Designated parking", "One-way trail system (~11 miles)"],
    mustSees: ["North of Dahlonega", "Marked one-way trails", "Easy to most difficult segments"],
    description:
      "About 11 miles of one-way OHV trails suitable for motorcycles and ATVs under 50\" wide. Located roughly 6 miles north of Dahlonega. Daylight use; stay on signed trails only.",
    notes: "Closed at night. Annual pass is valid across several Chattahoochee OHV systems.",
    activities: ["OHV / ATV", "Motorcycle"],
    ohvFriendly: true,
    dataSource: "curated",
    status: "open",
    access: "ohv_only",
    roadQuality: "gravel",
  },
  {
    id: "oakey-mountain-ohv",
    name: "Oakey Mountain OHV Trails",
    type: "ohv",
    agency: "USFS — Chattahoochee-Oconee NF (Chattooga River RD)",
    landManager: "USFS",
    lat: 34.82,
    lng: -83.55,
    elevation: 2200,
    driveTimeMinutes: 130,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "OHV pass required (day or annual)",
    parkingFee: "Trailhead parking",
    campingFee: "Trailhead / campground area nearby — confirm current status",
    maxStayDays: 14,
    amenities: ["Picnic area", "Vault toilet", "Trailhead on FS 161"],
    mustSees: ["Near Lake Burton / Lake Rabun", "Intermediate to rocky/steep terrain", "Width limit ~48\""],
    description:
      "OHV area near Lake Burton and Lake Rabun with two-way trails for vehicles under ~48\" axle width. Terrain ranges from intermediate to rocky and steep. Closes in wet conditions to protect resources.",
    notes: "Call Chattooga River Ranger District (706-754-6221) for weather closures before you go.",
    activities: ["OHV / ATV", "Motorcycle"],
    ohvFriendly: true,
    dataSource: "curated",
    status: "open",
    access: "ohv_only",
    roadQuality: "technical",
  },
  {
    id: "locust-stake-ohv",
    name: "Locust Stake OHV Trail System",
    type: "ohv",
    agency: "USFS — Chattahoochee-Oconee NF (Chattooga RD)",
    landManager: "USFS",
    lat: 34.75,
    lng: -83.35,
    elevation: 1600,
    driveTimeMinutes: 125,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: false,
    passRequired: "OHV trail permit required",
    parkingFee: "Limited staging parking",
    campingFee: "Overnight parking not permitted at staging",
    maxStayDays: 14,
    amenities: ["Staging with unloading ramp", "~10 miles of loops"],
    mustSees: ["Marked two-way loops", "Moderate difficulty", "North Fork Broad River area"],
    description:
      "Roughly 10 miles of two-way trail loops open to machines 48\" or less in width. Moderate difficulty; can be dusty when dry. Daylight riding only; overnight parking at the staging area is not allowed.",
    notes: "May close on short notice in wet weather. Check with the ranger station before heading out.",
    activities: ["OHV / ATV", "Motorcycle"],
    ohvFriendly: true,
    dataSource: "curated",
    status: "open",
    access: "ohv_only",
    roadQuality: "gravel",
  },
];

export const mockSites: CampSite[] = [...publicSites, ...privateNatureStays];

export function getSiteById(id: string): CampSite | undefined {
  return mockSites.find((s) => s.id === id);
}

export function getSitesByType(type: CampSite["type"]) {
  return mockSites.filter((s) => s.type === type);
}

export function getOhvSites() {
  return mockSites.filter((s) => s.ohvFriendly || s.type === "ohv");
}

export function getPrivateSites() {
  return mockSites.filter((s) => s.type === "private");
}
