import { CampSite } from "./types";

/**
 * Example private nature stays — Hipcamp-like access with hard caps
 * so the land stays nature, not a commercial campground.
 */
export const privateNatureStays: CampSite[] = [
  {
    id: "private-oakhaven-ridge",
    name: "Oakhaven Ridge (private nature stay)",
    type: "private",
    agency: "Private host",
    landManager: "Private",
    lat: 34.55,
    lng: -84.2,
    elevation: 1900,
    driveTimeMinutes: 95,
    hikeInMiles: 0,
    hikeInElevationGain: 0,
    reservationRequired: true,
    passRequired: "None — private land (host approval)",
    parkingFee: "Included",
    campingFee: "$35–$55 / night",
    maxStayDays: 3,
    amenities: ["Fire ring", "Flat tent pads", "Shared compost toilet", "Creek access on property"],
    mustSees: ["Ridge sunset", "Night sky", "Quiet hardwood forest"],
    description:
      "Two primitive tent sites on a private ridge north of Atlanta. No hookups, no rows of RVs — just woods, a shared compost toilet, and space to actually hear the land. Host lives on the property and keeps capacity low on purpose.",
    notes: "Max 2 sites. Leave No Trace. No generators. Dogs only if approved in advance.",
    activities: ["Camping", "Stargazing", "Walking the property"],
    dataSource: "private_host",
    status: "open",
    access: "any_vehicle",
    roadQuality: "gravel",
    pulse: {
      summary: "Quiet mid-week; host limits bookings so it never feels packed.",
      crowd: "quiet",
      roadNote: "Last half-mile is gravel; sedan-friendly when dry.",
      lastVerified: "2026-07",
      source: "curated",
    },
    privateHost: {
      hostName: "Example host",
      maxSites: 2,
      naturePledge: true,
      amenitiesAllowed: ["Fire ring", "Compost toilet", "Tent pads"],
      nightlyRate: "$35–$55",
      immersionRules: [
        "Maximum 2 tent sites — never expanded into a campground",
        "No RV hookups or permanent commercial infrastructure",
        "Guests pack out all trash",
        "Quiet hours after 10pm",
      ],
    },
  },
  {
    id: "private-millcreek-meadow",
    name: "Mill Creek Meadow (private nature stay)",
    type: "private",
    agency: "Private host",
    landManager: "Private",
    lat: 33.95,
    lng: -83.55,
    elevation: 700,
    driveTimeMinutes: 80,
    hikeInMiles: 0.15,
    hikeInElevationGain: 40,
    reservationRequired: true,
    passRequired: "None — private land",
    parkingFee: "Park at designated pull-off",
    campingFee: "$40 / night",
    maxStayDays: 2,
    amenities: ["One meadow site", "Creek within earshot", "No structures"],
    mustSees: ["Meadow at dusk", "Creek sounds", "Simple off-grid night"],
    description:
      "A single meadow site on private land east of Athens. Short walk from the parking pull-off. Intentionally one site only — the host refused to add more so the meadow stays a meadow.",
    notes: "True single-site immersion. No facilities. Bring water and pack out everything.",
    activities: ["Camping", "Quiet reading", "Creek time"],
    dataSource: "private_host",
    status: "open",
    access: "any_vehicle",
    roadQuality: "gravel",
    pulse: {
      summary: "One site by design. Feels remote without a long drive.",
      crowd: "quiet",
      lastVerified: "2026-06",
      source: "curated",
    },
    privateHost: {
      hostName: "Example host",
      maxSites: 1,
      naturePledge: true,
      amenitiesAllowed: ["None — pure primitive"],
      nightlyRate: "$40",
      immersionRules: [
        "One site only — never more",
        "No permanent structures for guests",
        "Leave No Trace",
        "Host may pause bookings during sensitive seasons",
      ],
    },
  },
];
