import type { MetadataRoute } from 'next';

// Generated by app-engine: scripts/add-seo-surface.mjs
// Re-run that script after adding pages so search engines see them.
const BASE_URL = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://immerse-coral.vercel.app';

const ROUTES: Array<{ path: string; priority: number }> = [
  { path: '/', priority: 1 },
  { path: '/host', priority: 0.8 },
  { path: '/policy/severe-abuse', priority: 0.6 },
  { path: '/search', priority: 0.8 },
  { path: '/trips', priority: 0.8 },
  { path: '/trust', priority: 0.8 },
];

export default function sitemap(): MetadataRoute.Sitemap {
  const lastModified = new Date();
  return ROUTES.map(({ path, priority }) => ({
    url: `${BASE_URL}${path === '/' ? '' : path}`,
    lastModified,
    changeFrequency: priority === 1 ? 'weekly' : 'monthly',
    priority,
  }));
}
